### ISSUE TITLE
a4j onComplete functions do not work properly

### ISSUE THREAD

**Issue by wlhUser** [albfernandez/richfaces#25]
I've just downloaded richfaces 4.6.6ayg in order to test if my project, whic is running fine with richfaces 4.5.15.Final, can be ported to RF4.6.6ayg.

However I've noticed a problem in the 'oncomplete' function of the a4j:commandLink. 

**Example**:
_<a4j:commandLink action="#{bean.incrementValueA()}" 
   value="#{bean.valueA}" 
   render="@this"
   oncomplete="alert('Hello, value = #{bean.valueA}');" 
/>_

_public class Bean {
   private long valueA = 0;
   public void incrementValueA() {
        valueA++;
    }
    public long getValueA() {
        return valueA;
    }
}_

In RF4.5.15, the link value shown on the GUI (after clicking) is always the one shown in the alert box.
In RF 4.6.6ayg, the link value shown on the GUI is shown correctly, but the one in the alert box shows the value **before** it was incremented.

A similar behavior occurs if I use '#{facesContext.maximumSeverity}' in the 'oncomplete' function. In 4.5.15 it always returns correct values, while in 4.6.6ayg it never returns a value.

According to my rudimentary debugging the oncomplete function in 4.6.6ayg is being rendered in the 'ApplyRequestValues' phase which is too early in my opinion. In 4.5.15 it is being rendered in the RenderResponse phase, which is correct.

--------------------------------------------------------------------------------------------------------
**NOTICE:** **According to further tests, the problem occurs only in case PrimeFaces6.2 is used in the same project. Hence I suppose the problem is not related to Richfaces.**

**Comment by wlhUser** [comment]
Hi Alberto,

I'm not sure if you have time for my requests, but if yes, I'd like to discuss a bug (at least in my opinion) in Richfaces, which leads to the behavior described above, in case Primefaces 6.2 is used as well.

With PrimeFaces > 6.0 a PhaseListener for the **RESTORE_VIEW** Phase (org.primefaces.application.resource.DynamicResourcesPhaseListener) has been modified. Now it calls amongst others in the afterPhasse method, the following method:


```
public void afterPhase(PhaseEvent event) {
…

// skip update=@all as the head will all resources will already be rendered
        if (context.getPartialViewContext().isRenderAll()) {
            return;
        }
…

}
```
The PartialViewContext on which **isRenderAll()** is called, is an object of the class **org.richfaces.context. ExtendedPartialViewContext**. The isRenderAll() method in this class, calls the *detectRenderAll()*, method, and this method does not only detect, but changes **org.richfaces.context.ActivatorComponentRenderCallback** objects by calling **visitActivatorAtRender()**;. visitActivatorAtRender() maintains an internal flag *isActivatorVisitedAtRender* which should ensure that the method is called only once per object and request cycle. 

For this reason I would modify the method **ExtendedPartialViewContext.detectRenderAll()** 

**From:**


```
private boolean detectRenderAll() {
        // RF-13740, MyFaces doesn't call for renderIds in advance

        if (renderIds == null) {
            renderIds = new LinkedHashSet<String>();
            visitActivatorAtRender();
        }

        return Boolean.TRUE.equals(renderAll) || renderIds.contains(ALL);
    }
```

**To:**

```
private boolean detectRenderAll() {
        // RF-13740, MyFaces doesn't call for renderIds in advance
        if (renderIds == null) {
            renderIds = new LinkedHashSet<String>();
            PhaseId currenPhaseId = facesContext.getCurrentPhaseId();
            // NEW: Do this only in the RENDER_RESPONSE Phase
            if (currenPhaseId == PhaseId.RENDER_RESPONSE) {
                visitActivatorAtRender();
            }
        }

        return Boolean.TRUE.equals(renderAll) || renderIds.contains(ALL);
    }
```


I’m not sure if you are familiar with this part of RF and can judge if my proposed changes are correct – at least I can confirm that the test case I’ve described in my post works now.

What do you think?

Regards

Holger

**Comment by albfernandez** [comment]
I've been testing your patch in the showcase. it "fails" in the ajax-queue example. The field is disabled

disabled="#{not (facesContext.maximumSeverity==null)}" 

I'll continue investigating

**Comment by wlhUser** [comment]
Thanks for testing my patch. What a pity that it does not work in one test case. I will also continue investigating. My first approach was to fix only the problem triggered by the PrimeFaces PhaseListener and excluding only the RESTORE_VIEW Phase in the detectRenderAll method, but this would by a real dirty hack.

**Comment by wlhUser** [comment]
I did a test with the ajax-queue demo, with my patched version of RF 4.6.6, and it worked fine. At least my manual tests. I never had a problem with `disabled="#{not (facesContext.maximumSeverity==null)}"`.
I would be interesting to see which error message was contained in your case in the facesContext.

**Comment by albfernandez** [comment]
I did a new test and all is working fine, maybe a strange bug in showcase. I'll include your path right now, Thanks

**Comment by wlhUser** [comment]
Thank you for merging my patch.
Just for my information, when do you plan to release a new RF version?

**Comment by albfernandez** [comment]
this weekend, maybe (I'll try)

**Comment by wlhUser** [comment]
Thank you for the new version.
