### ISSUE TITLE
Cannot determine module name for richfaces-core 4.6.12.ayg

### ISSUE THREAD

**Issue by hazendaz** [albfernandez/richfaces#39]
This error occurs during javadoc report generation with higher jdks.  I think the solution is rather simple in just needing to define automatic module naming which is added to the meta data of the jars.  Is it possible automatic module naming can be added to the core components here and a quick patch released?

**Comment by albfernandez** [comment]
I think Automatic-Module-Name is already added in all META-INF/MANIFEST.MF.
What are you doing? the problem is compiling your project or Richfaces itfself?

**Comment by hazendaz** [comment]
Compiling my project.  Javadoc plugin run states that its unable to determine the module name for rich faces.  I'll look a little deeper and get you better info later thus weekend.  It is the only lib out of around 200 in the build with any issue.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
@albfernandez Closing.  Found the source of issue.  Someone in my firm manually uploaded jboss 6.0 pom 3 years ago and it causes a cascading issue that results in this appearance.  So this is not an issue here and therefore nothing is needed to be done.  Thanks.
