### ISSUE TITLE
upgrade to JQuery 3

### ISSUE THREAD

**Issue by albfernandez** [albfernandez/richfaces#6]

**Comment by Quix0r** [comment]
I would recommend to use jquery-migrate in debug mode until you have found all deprecated features and flaws. Then use the release (non-dev) version to have full performance. You can find it [here on github](https://github.com/jquery/jquery-migrate).

**Comment by albfernandez** [comment]
Thanks for your tip.
I'll create a new branch for the migration

**Comment by Quix0r** [comment]
Quick note: With debug mode, the uncompressed (not minimized) version is meant.
