### ISSUE TITLE
Release 4.6.14

### ISSUE THREAD

**Issue by saknopper** [albfernandez/richfaces#63]
Hi Alberto,

Are there things you want to improve/fix before releasing version 4.6.14 and I can help with?

Otherwise it might be a good time to make a release. I think we've done quite some improvements and cleanups since the last release. I have some other things I'd like to improve, but that's a bit more work and it might take a while before it's finished.

**Comment by albfernandez** [comment]
I've released 4.6.14 just now
Thanks for your contributions.

**Comment by saknopper** [comment]
Great, thank you!
