### ISSUE TITLE
Remove phantomjs dependencie

### ISSUE THREAD

**Issue by albfernandez** [albfernandez/richfaces#68]

**Comment by jimmywarting** [comment]
PhantomJS is pretty much dead now.
It's a old headless browser that no real user have ever used and was solo created for developers to automate & scrape stuff.
it don't get any more updates and are now archived/suspended for a long time now

ppl should just stop using it and switch to something like puppeteer instead.

**Comment by albfernandez** [comment]
Yes, they state project is frozen since 2018, almost four years 

Quote from their home page.
"Important: PhantomJS development is suspended until further notice (see [https://github.com/ariya/phantomjs/issues/15343](https://github.com/ariya/phantomjs/issues/15343) more details)."

it's a shame because it allowed to run the tests without additional configuration, but it is difficult to keep it running and it'll be worse in the future.

So, I'll change the issue to remove phantomjs tests (currently they are broken, and seems difficult or impossible to fix without using very old dependencies)

**Comment by albfernandez** [comment]
We can use chrome as default driver for testing.

**Comment by albfernandez** [comment]
Phantomjs removed in a0481ba3acc093356da7da9b730052913b310faf
