### ISSUE TITLE
Replace custom log4j with more official reload4j?

### ISSUE THREAD

**Issue by hazendaz** [albfernandez/richfaces#69]
This is probably a better approach given it will get more support.  Not sure if all cve's fixed here or not.  Personally I exclude this anyways and use slf4j/logback but figure it might be worthwhile to rebasee your log4j against the new project that was raised up and see if there was other specific value more can benefit from.

https://github.com/qos-ch/reload4j

**Comment by albfernandez** [comment]
Thanks a lot
I will do it right now.
